# Generated by Django 3.0.1 on 2019-12-28 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=4)),
                ('synopsis', models.CharField(max_length=800)),
                ('release_date', models.DateField(default=datetime.datetime(2019, 12, 28, 9, 36, 11, 971310))),
                ('movie_week', models.BooleanField(default=True)),
                ('next_week', models.BooleanField(default=False)),
                ('urlimage', models.FileField(null=True, upload_to='peliculas/%Y/%m/%d')),
                ('videointro', models.CharField(max_length=400, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peliculas.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(to='peliculas.Movie')),
            ],
        ),
    ]
