# Generated by Django 3.0.1 on 2019-12-31 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20191231_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 31, 16, 47, 32, 135823)),
        ),
    ]
