# Generated by Django 3.0.1 on 2020-01-10 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_auto_20200110_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 13, 54, 28, 175421)),
        ),
    ]
