# Generated by Django 3.0.1 on 2020-01-10 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_auto_20200110_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movies',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(related_name='movie', to='peliculas.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 17, 24, 38, 616737)),
        ),
    ]
