# Generated by Django 3.0.1 on 2020-01-10 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_auto_20200110_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(to='peliculas.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 17, 59, 50, 255885)),
        ),
    ]
