# Generated by Django 3.0.1 on 2020-01-15 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_auto_20200110_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 14, 22, 24, 20, 182222)),
        ),
    ]
