# Generated by Django 3.0.1 on 2020-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Usuario', 'Usuario'), ('Asistente', 'Asistente'), ('Administrador', 'Administrador')], null=True),
        ),
    ]
