# Generated by Django 3.0.1 on 2020-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200110_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Usuario', 'Usuario'), ('Asistente', 'Asistente'), ('Administrador', 'Administrador')], max_length=14, null=True),
        ),
    ]
