# Generated by Django 3.0.1 on 2020-01-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0014_auto_20200114_2224'),
        ('teatros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.IntegerField()),
                ('seats_number', models.IntegerField()),
                ('format', models.ManyToManyField(to='teatros.Format')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatros.Theater')),
            ],
        ),
        migrations.CreateModel(
            name='MovieFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats_sold', models.IntegerField()),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatros.Format')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatros.Hour')),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatros.Lounge')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peliculas.Movie')),
            ],
        ),
    ]
